/*
 * IDENTIFICATION:
 * stub generated Sun Mar 11 17:57:25 2018
 * with a MiG generated by bootstrap_cmds-96.20.2
 * OPTIONS: 
 */

/* Module job_reply */

#define	__MIG_check__Request__job_reply_subsystem__ 1

#include <string.h>
#include <mach/ndr.h>
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/message.h>
#include <mach/mig_errors.h>
#include <mach/port.h>
	
/* BEGIN VOUCHER CODE */

#ifndef KERNEL
#if defined(__has_include)
#if __has_include(<mach/mig_voucher_support.h>)
#ifndef USING_VOUCHERS
#define USING_VOUCHERS
#endif
#ifndef __VOUCHER_FORWARD_TYPE_DECLS__
#define __VOUCHER_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif // __VOUCHER_FORWARD_TYPE_DECLS__
#endif // __has_include(<mach/mach_voucher_types.h>)
#endif // __has_include
#endif // !KERNEL
	
/* END VOUCHER CODE */

	
/* BEGIN MIG_STRNCPY_ZEROFILL CODE */

#if defined(__has_include)
#if __has_include(<mach/mig_strncpy_zerofill_support.h>)
#ifndef USING_MIG_STRNCPY_ZEROFILL
#define USING_MIG_STRNCPY_ZEROFILL
#endif
#ifndef __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#define __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern int mig_strncpy_zerofill(char *dest, const char *src, int len) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif /* __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__ */
#endif /* __has_include(<mach/mig_strncpy_zerofill_support.h>) */
#endif /* __has_include */
	
/* END MIG_STRNCPY_ZEROFILL CODE */


#include <mach/std_types.h>
#include <mach/mig.h>
#include <mach/mig.h>
#include <mach/mach_types.h>
#include "bootstrap.h"
#include "vproc.h"
#include "vproc_internal.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* typedefs for all requests */

#ifndef __Request__job_reply_subsystem__defined
#define __Request__job_reply_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t kr;
	} __Request__job_mig_send_signal_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t outval;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t outvalCnt;
	} __Request__job_mig_log_drain_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t obsrvp;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		pid_t pid;
	} __Request__job_mig_spawn2_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Request__job_reply_subsystem__defined */

/* typedefs for all replies */

#ifndef __Reply__job_reply_subsystem__defined
#define __Reply__job_reply_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__job_mig_send_signal_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__job_mig_log_drain_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__job_mig_spawn2_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Reply__job_reply_subsystem__defined */


/* union of all replies */

#ifndef __ReplyUnion__job_reply_subsystem__defined
#define __ReplyUnion__job_reply_subsystem__defined
union __ReplyUnion__job_reply_subsystem {
	__Reply__job_mig_send_signal_reply_t Reply_job_mig_send_signal_reply;
	__Reply__job_mig_log_drain_reply_t Reply_job_mig_log_drain_reply;
	__Reply__job_mig_spawn2_reply_t Reply_job_mig_spawn2_reply;
};
#endif /* __RequestUnion__job_reply_subsystem__defined */
/* Forward Declarations */


mig_internal novalue _Xjob_mig_send_signal_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xjob_mig_log_drain_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xjob_mig_spawn2_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__job_reply_subsystem__
#if !defined(__MIG_check__Request__job_mig_send_signal_reply_t__defined)
#define __MIG_check__Request__job_mig_send_signal_reply_t__defined

mig_internal kern_return_t __MIG_check__Request__job_mig_send_signal_reply_t(__attribute__((__unused__)) __Request__job_mig_send_signal_reply_t *In0P)
{

	typedef __Request__job_mig_send_signal_reply_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__job_mig_send_signal_reply_t__defined) */
#endif /* __MIG_check__Request__job_reply_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* SimpleRoutine job_mig_send_signal_reply */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t job_mig_send_signal_reply
(
	mach_port_t rp,
	kern_return_t kr
);

/* SimpleRoutine job_mig_send_signal_reply */
mig_internal novalue _Xjob_mig_send_signal_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t kr;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__job_mig_send_signal_reply_t __Request;
	typedef __Reply__job_mig_send_signal_reply_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__job_mig_send_signal_reply_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__job_mig_send_signal_reply_t__defined */

	__DeclareRcvSimple(505, "job_mig_send_signal_reply")
	__BeforeRcvSimple(505, "job_mig_send_signal_reply")

#if	defined(__MIG_check__Request__job_mig_send_signal_reply_t__defined)
	check_result = __MIG_check__Request__job_mig_send_signal_reply_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__job_mig_send_signal_reply_t__defined) */

    // _sjc_ 'use of undeclared identifier kr' (in a mig generated file...)
    // going to pass in the check_result instead
	OutP->RetCode = job_mig_send_signal_reply(In0P->Head.msgh_request_port, check_result /*kr*/);
	__AfterRcvSimple(505, "job_mig_send_signal_reply")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__job_reply_subsystem__
#if !defined(__MIG_check__Request__job_mig_log_drain_reply_t__defined)
#define __MIG_check__Request__job_mig_log_drain_reply_t__defined

mig_internal kern_return_t __MIG_check__Request__job_mig_log_drain_reply_t(__attribute__((__unused__)) __Request__job_mig_log_drain_reply_t *In0P)
{

	typedef __Request__job_mig_log_drain_reply_t __Request;
#if	__MigTypeCheck
	if ((!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request))) &&
	    ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    In0P->Head.msgh_size != (mach_msg_size_t)sizeof(mig_reply_error_t) ||
	    ((mig_reply_error_t *)In0P)->RetCode == KERN_SUCCESS))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->outval.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->outval.size != In0P->outvalCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__job_mig_log_drain_reply_t__defined) */
#endif /* __MIG_check__Request__job_reply_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* SimpleRoutine job_mig_log_drain_reply */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t job_mig_log_drain_reply
(
	mach_port_t rp,
	kern_return_t kr,
	vm_offset_t outval,
	mach_msg_type_number_t outvalCnt
);

/* SimpleRoutine job_mig_log_drain_reply */
mig_internal novalue _Xjob_mig_log_drain_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t outval;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t outvalCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__job_mig_log_drain_reply_t __Request;
	typedef __Reply__job_mig_log_drain_reply_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__job_mig_log_drain_reply_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__job_mig_log_drain_reply_t__defined */

	__DeclareRcvSimple(521, "job_mig_log_drain_reply")
	__BeforeRcvSimple(521, "job_mig_log_drain_reply")
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) &&
	    (In0P->Head.msgh_size == (mach_msg_size_t)sizeof(mig_reply_error_t)))
	{
	OutP->RetCode = job_mig_log_drain_reply(In0P->Head.msgh_request_port, ((mig_reply_error_t *)In0P)->RetCode, (vm_offset_t)(0), (mach_msg_type_number_t)(0));
	return;
	}

#if	defined(__MIG_check__Request__job_mig_log_drain_reply_t__defined)
	check_result = __MIG_check__Request__job_mig_log_drain_reply_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__job_mig_log_drain_reply_t__defined) */

	OutP->RetCode = job_mig_log_drain_reply(In0P->Head.msgh_request_port, KERN_SUCCESS, (vm_offset_t)(In0P->outval.address), In0P->outval.size);
	__AfterRcvSimple(521, "job_mig_log_drain_reply")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__job_reply_subsystem__
#if !defined(__MIG_check__Request__job_mig_spawn2_reply_t__defined)
#define __MIG_check__Request__job_mig_spawn2_reply_t__defined

mig_internal kern_return_t __MIG_check__Request__job_mig_spawn2_reply_t(__attribute__((__unused__)) __Request__job_mig_spawn2_reply_t *In0P)
{

	typedef __Request__job_mig_spawn2_reply_t __Request;
#if	__MigTypeCheck
	if ((!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request))) &&
	    ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    In0P->Head.msgh_size != (mach_msg_size_t)sizeof(mig_reply_error_t) ||
	    ((mig_reply_error_t *)In0P)->RetCode == KERN_SUCCESS))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->obsrvp.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->obsrvp.disposition != 16)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__job_mig_spawn2_reply_t__defined) */
#endif /* __MIG_check__Request__job_reply_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* SimpleRoutine job_mig_spawn2_reply */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t job_mig_spawn2_reply
(
	mach_port_t rp,
	kern_return_t kr,
	pid_t pid,
	mach_port_t obsrvp
);

/* SimpleRoutine job_mig_spawn2_reply */
mig_internal novalue _Xjob_mig_spawn2_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t obsrvp;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		pid_t pid;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__job_mig_spawn2_reply_t __Request;
	typedef __Reply__job_mig_spawn2_reply_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__job_mig_spawn2_reply_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__job_mig_spawn2_reply_t__defined */

	__DeclareRcvSimple(535, "job_mig_spawn2_reply")
	__BeforeRcvSimple(535, "job_mig_spawn2_reply")
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) &&
	    (In0P->Head.msgh_size == (mach_msg_size_t)sizeof(mig_reply_error_t)))
	{
	OutP->RetCode = job_mig_spawn2_reply(In0P->Head.msgh_request_port, ((mig_reply_error_t *)In0P)->RetCode, (pid_t)(0), (mach_port_t)(0));
	return;
	}

#if	defined(__MIG_check__Request__job_mig_spawn2_reply_t__defined)
	check_result = __MIG_check__Request__job_mig_spawn2_reply_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__job_mig_spawn2_reply_t__defined) */

	OutP->RetCode = job_mig_spawn2_reply(In0P->Head.msgh_request_port, KERN_SUCCESS, In0P->pid, In0P->obsrvp.name);
	__AfterRcvSimple(535, "job_mig_spawn2_reply")
}


#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
boolean_t job_reply_server(
		mach_msg_header_t *InHeadP,
		mach_msg_header_t *OutHeadP);

#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
mig_routine_t job_reply_server_routine(
		mach_msg_header_t *InHeadP);


/* Description of this subsystem, for use in direct RPC */
const struct job_reply_subsystem {
	mig_server_routine_t 	server;	/* Server routine */
	mach_msg_id_t	start;	/* Min routine number */
	mach_msg_id_t	end;	/* Max routine number + 1 */
	unsigned int	maxsize;	/* Max msg size */
	vm_address_t	reserved;	/* Reserved */
	struct routine_descriptor	/*Array of routine descriptors */
		routine[38];
} job_reply_subsystem = {
	job_reply_server_routine,
	500,
	538,
	(mach_msg_size_t)sizeof(union __ReplyUnion__job_reply_subsystem),
	(vm_address_t)0,
	{
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xjob_mig_send_signal_reply, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__job_mig_send_signal_reply_t)},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xjob_mig_log_drain_reply, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__job_mig_log_drain_reply_t)},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xjob_mig_spawn2_reply, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__job_mig_spawn2_reply_t)},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
	}
};

mig_external boolean_t job_reply_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 537) || (InHeadP->msgh_id < 500) ||
	    ((routine = job_reply_subsystem.routine[InHeadP->msgh_id - 500].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t job_reply_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 500;

	if ((msgh_id > 37) || (msgh_id < 0))
		return 0;

	return job_reply_subsystem.routine[msgh_id].stub_routine;
}
