/*
 * IDENTIFICATION:
 * stub generated Sun Mar 11 17:57:25 2018
 * with a MiG generated by bootstrap_cmds-96.20.2
 * OPTIONS: 
 */
#define	__MIG_check__Reply__job_reply_subsystem__ 1

#include "job_reply.h"


#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__MachMsgErrorWithTimeout
#define	__MachMsgErrorWithTimeout(_R_) { \
	switch (_R_) { \
	case MACH_SEND_INVALID_DATA: \
	case MACH_SEND_INVALID_DEST: \
	case MACH_SEND_INVALID_HEADER: \
		mig_put_reply_port(InP->Head.msgh_reply_port); \
		break; \
	case MACH_SEND_TIMED_OUT: \
	case MACH_RCV_TIMED_OUT: \
	default: \
		mig_dealloc_reply_port(InP->Head.msgh_reply_port); \
	} \
}
#endif	/* __MachMsgErrorWithTimeout */

#ifndef	__MachMsgErrorWithoutTimeout
#define	__MachMsgErrorWithoutTimeout(_R_) { \
	switch (_R_) { \
	case MACH_SEND_INVALID_DATA: \
	case MACH_SEND_INVALID_DEST: \
	case MACH_SEND_INVALID_HEADER: \
		mig_put_reply_port(InP->Head.msgh_reply_port); \
		break; \
	default: \
		mig_dealloc_reply_port(InP->Head.msgh_reply_port); \
	} \
}
#endif	/* __MachMsgErrorWithoutTimeout */

#ifndef	__DeclareSendRpc
#define	__DeclareSendRpc(_NUM_, _NAME_)
#endif	/* __DeclareSendRpc */

#ifndef	__BeforeSendRpc
#define	__BeforeSendRpc(_NUM_, _NAME_)
#endif	/* __BeforeSendRpc */

#ifndef	__AfterSendRpc
#define	__AfterSendRpc(_NUM_, _NAME_)
#endif	/* __AfterSendRpc */

#ifndef	__DeclareSendSimple
#define	__DeclareSendSimple(_NUM_, _NAME_)
#endif	/* __DeclareSendSimple */

#ifndef	__BeforeSendSimple
#define	__BeforeSendSimple(_NUM_, _NAME_)
#endif	/* __BeforeSendSimple */

#ifndef	__AfterSendSimple
#define	__AfterSendSimple(_NUM_, _NAME_)
#endif	/* __AfterSendSimple */

#define msgh_request_port	msgh_remote_port
#define msgh_reply_port		msgh_local_port



/* SimpleRoutine job_mig_send_signal_reply */
mig_external kern_return_t job_mig_send_signal_reply
(
	mach_port_t rp,
	kern_return_t kr
)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t kr;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
	} Mess;

	Request *InP = &Mess.In;

	mach_msg_return_t msg_result;

#ifdef	__MIG_check__Reply__job_mig_send_signal_reply_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__job_mig_send_signal_reply_t__defined */

	__DeclareSendSimple(505, "job_mig_send_signal_reply")

	InP->NDR = NDR_record;

	InP->kr = kr;

	InP->Head.msgh_bits =
		MACH_MSGH_BITS(18, 0);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = rp;
	InP->Head.msgh_reply_port = MACH_PORT_NULL;
	InP->Head.msgh_id = 505;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendSimple(505, "job_mig_send_signal_reply")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_MSG_OPTION_NONE, (mach_msg_size_t)sizeof(Request), 0, MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendSimple(505, "job_mig_send_signal_reply")
	return msg_result;
}

/* SimpleRoutine job_mig_log_drain_reply */
mig_external kern_return_t job_mig_log_drain_reply
(
	mach_port_t rp,
	kern_return_t kr,
	vm_offset_t outval,
	mach_msg_type_number_t outvalCnt
)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t outval;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t outvalCnt;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
	} Mess;

	Request *InP = &Mess.In;

	mach_msg_return_t msg_result;

#ifdef	__MIG_check__Reply__job_mig_log_drain_reply_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__job_mig_log_drain_reply_t__defined */

	__DeclareSendSimple(521, "job_mig_log_drain_reply")

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t outvalTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	if (kr) {
		((mig_reply_error_t *)InP)->RetCode = kr;
		((mig_reply_error_t *)InP)->NDR = NDR_record;
		goto ready_to_send;
	}

	InP->msgh_body.msgh_descriptor_count = 1;
#if	UseStaticTemplates
	InP->outval = outvalTemplate;
	InP->outval.address = (void *)(outval);
	InP->outval.size = outvalCnt;
#else	/* UseStaticTemplates */
	InP->outval.address = (void *)(outval);
	InP->outval.size = outvalCnt;
	InP->outval.deallocate =  FALSE;
	InP->outval.copy = MACH_MSG_VIRTUAL_COPY;
	InP->outval.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */

	InP->NDR = NDR_record;

	InP->outvalCnt = outvalCnt;

ready_to_send:
	InP->Head.msgh_bits =
		MACH_MSGH_BITS(18, 0);
	if (!kr)
		InP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = rp;
	InP->Head.msgh_reply_port = MACH_PORT_NULL;
	InP->Head.msgh_id = 521;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendSimple(521, "job_mig_log_drain_reply")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_MSG_OPTION_NONE, (kr) ? (mach_msg_size_t)sizeof(mig_reply_error_t) : (mach_msg_size_t)sizeof(Request), 0, MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendSimple(521, "job_mig_log_drain_reply")
	return msg_result;
}

/* SimpleRoutine job_mig_spawn2_reply */
mig_external kern_return_t job_mig_spawn2_reply
(
	mach_port_t rp,
	kern_return_t kr,
	pid_t pid,
	mach_port_t obsrvp
)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t obsrvp;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		pid_t pid;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
	} Mess;

	Request *InP = &Mess.In;

	mach_msg_return_t msg_result;

#ifdef	__MIG_check__Reply__job_mig_spawn2_reply_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__job_mig_spawn2_reply_t__defined */

	__DeclareSendSimple(535, "job_mig_spawn2_reply")

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t obsrvpTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		16,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	if (kr) {
		((mig_reply_error_t *)InP)->RetCode = kr;
		((mig_reply_error_t *)InP)->NDR = NDR_record;
		goto ready_to_send;
	}

	InP->msgh_body.msgh_descriptor_count = 1;
#if	UseStaticTemplates
	InP->obsrvp = obsrvpTemplate;
	InP->obsrvp.name = obsrvp;
#else	/* UseStaticTemplates */
	InP->obsrvp.name = obsrvp;
	InP->obsrvp.disposition = 16;
	InP->obsrvp.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */

	InP->NDR = NDR_record;

	InP->pid = pid;

ready_to_send:
	InP->Head.msgh_bits =
		MACH_MSGH_BITS(18, 0);
	if (!kr)
		InP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = rp;
	InP->Head.msgh_reply_port = MACH_PORT_NULL;
	InP->Head.msgh_id = 535;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendSimple(535, "job_mig_spawn2_reply")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_MSG_OPTION_NONE, (kr) ? (mach_msg_size_t)sizeof(mig_reply_error_t) : (mach_msg_size_t)sizeof(Request), 0, MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendSimple(535, "job_mig_spawn2_reply")
	return msg_result;
}
